spring:
  application:
    name: Dream_shop

  datasource:
    url:  ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 8MB

server:
  port: 8080

api:
  prefix: /Dream_shop/web

auth:
  token:
    expirationInMils: 3600000
    jwtSecret: 123456789DivyanshUpadhyay1284639273fnfjfujsarfbfrffdxfosfk0smxjvdufzofdnfujgmfiueishgkxkejkfbsmfdjkfns
